export type CaseStatus = "Discovery" | "In Progress" | "Review" | "Ready for Handoff" | "Issued";
export type ProductType = "IFA" | "Participating Whole Life" | "Universal Life" | "Term Life";

export interface TimelineEvent {
  label: string;
  date: string;
  completed: boolean;
}

export interface ActivityLogEntry {
  action: string;
  timestamp: string;
}

export interface AIHistoryEntry {
  question: string;
  response: string;
  timestamp: string;
}

export interface Case {
  id: string;
  client: string;
  age: number;
  product: ProductType;
  status: CaseStatus;
  premium: string;
  carrier: string;
  advisor: string;
  created: string;
  updated: string;
  email: string;
  phone: string;
  dob: string;
  occupation: string;
  income: string;
  riskProfile: string;
  goals: string[];
  notes: string;
  complianceComplete: boolean;
  complianceMissing?: string[];
  suitabilityNarrative: string;
  timeline: TimelineEvent[];
  activityLog: ActivityLogEntry[];
  aiHistory: AIHistoryEntry[];
}

// Canadian mock cases focusing on IFAs (Immediate Financing Arrangements)
// and permanent life insurance for BC advisors
export const MOCK_CASES: Case[] = [
  {
    id: "IFA-2026-001",
    client: "Chen Holdings Ltd. (David & Michelle Chen)",
    age: 52,
    product: "IFA",
    status: "In Progress",
    premium: "$150,000",
    carrier: "Manulife",
    advisor: "Sarah Thompson",
    created: "Jan 15, 2026",
    updated: "2 hours ago",
    email: "david.chen@chenholdings.ca",
    phone: "(604) 555-2341",
    dob: "03/12/1974",
    occupation: "Business Owner (CCPC - Software Development)",
    income: "$450,000 (corporate retained earnings)",
    riskProfile: "Moderate",
    goals: ["Tax-Efficient Wealth Accumulation", "Estate Planning", "Corporate Surplus Investment"],
    notes: "Corporation has $2M in retained earnings. Seeking tax-efficient alternative to corporate GICs. Wants to create CDA for future tax-free distributions. Spouse is co-shareholder.",
    complianceComplete: true,
    suitabilityNarrative: "Based on Chen Holdings Ltd.'s financial profile, including $2M in corporate retained earnings, the principals' ages (52 & 50), and primary objectives of tax-efficient wealth accumulation and estate planning, a Manulife Participating Whole Life policy structured as an Immediate Financing Arrangement is the most suitable recommendation. The IFA structure will create Capital Dividend Account (CDA) credits upon death, allow NCPI deductions to reduce corporate taxable income, and provide tax-deferred cash value growth superior to taxable corporate investments. The $150,000 annual premium represents a prudent allocation of corporate surplus and aligns with the corporation's long-term financial strategy.",
    timeline: [
      { label: "Case created", date: "Jan 15, 2026", completed: true },
      { label: "Discovery started", date: "Jan 15, 2026", completed: true },
      { label: "Corporate structure reviewed", date: "Jan 16, 2026", completed: true },
      { label: "Tax advisor consulted", date: "Jan 18, 2026", completed: true },
      { label: "Suitability approved", date: "Jan 20, 2026", completed: true },
      { label: "Handoff package generated", date: "Pending", completed: false },
    ],
    activityLog: [
      { action: "Case created by Sarah Thompson", timestamp: "Jan 15, 2026 — 9:00 AM" },
      { action: "Discovery Step 1 (Corporate Info) completed", timestamp: "Jan 15, 2026 — 9:30 AM" },
      { action: "Discovery Step 2 (Financial Profile) completed", timestamp: "Jan 15, 2026 — 10:15 AM" },
      { action: "Reviewed T2 corporate tax returns", timestamp: "Jan 16, 2026 — 2:00 PM" },
      { action: "Consultation with client's accountant (CDA projections)", timestamp: "Jan 18, 2026 — 11:00 AM" },
      { action: "IFA suitability narrative generated by AI", timestamp: "Jan 20, 2026 — 3:15 PM" },
      { action: "Suitability determination approved", timestamp: "Jan 20, 2026 — 4:00 PM" },
    ],
    aiHistory: [
      { question: "Explain how CDA credits work in an IFA structure for a BC corporation", response: "In an Immediate Financing Arrangement, when the insured person passes away, the death benefit paid to the corporation generates a credit to the Capital Dividend Account (CDA) equal to the death benefit minus the policy's Adjusted Cost Basis (ACB). This CDA credit allows the corporation to pay tax-free dividends to shareholders under ITA 83(2). For example, a $2M death benefit with $200K ACB creates $1.8M in CDA credits, allowing $1.8M in tax-free distributions. This is significantly more tax-efficient than regular corporate dividends which are taxable to shareholders.", timestamp: "Jan 16, 2026 — 10:30 AM" },
      { question: "Generate IFA suitability narrative for Chen Holdings Ltd.", response: "Based on Chen Holdings Ltd.'s financial profile, including $2M in corporate retained earnings, the principals' ages (52 & 50), and primary objectives of tax-efficient wealth accumulation and estate planning, a Manulife Participating Whole Life policy structured as an Immediate Financing Arrangement is the most suitable recommendation.", timestamp: "Jan 20, 2026 — 3:15 PM" },
    ],
  },
  {
    id: "PAR-2026-008",
    client: "Dr. Priya Sharma & Dr. Raj Sharma",
    age: 58,
    product: "Participating Whole Life",
    status: "Ready for Handoff",
    premium: "$75,000",
    carrier: "Equitable Life Canada",
    advisor: "Sarah Thompson",
    created: "Jan 22, 2026",
    updated: "Yesterday",
    email: "p.sharma@coastalmedical.ca",
    phone: "(604) 555-7892",
    dob: "07/15/1968",
    occupation: "Physicians (Medical Corporation)",
    income: "$850,000 (combined through professional corp)",
    riskProfile: "Moderately Conservative",
    goals: ["Estate Equalization", "Tax-Free Legacy", "Supplemental Retirement Income"],
    notes: "Dual physician household with professional corporation. Two adult children - want to leave equal estates. Already maximized RRSPs and TFSAs. Looking for participating whole life for estate planning and potential policy loan retirement income.",
    complianceComplete: true,
    suitabilityNarrative: "Dr. Sharma and Dr. Sharma's moderately conservative risk profile, strong income through their medical corporation, and objectives of estate equalization and tax-efficient legacy planning make Equitable EquiPar the most suitable product. The participating whole life policy provides guaranteed death benefit with dividend potential, can be owned by their professional corporation for additional tax efficiency, and allows policy loan access for supplemental retirement income. The $75,000 annual premium is well within their means and represents appropriate diversification beyond their RRSP/TFSA holdings.",
    timeline: [
      { label: "Case created", date: "Jan 22, 2026", completed: true },
      { label: "Discovery started", date: "Jan 22, 2026", completed: true },
      { label: "Medical underwriting completed", date: "Jan 25, 2026", completed: true },
      { label: "Suitability approved", date: "Jan 27, 2026", completed: true },
      { label: "Handoff package generated", date: "Jan 29, 2026", completed: true },
    ],
    activityLog: [
      { action: "Case created by Sarah Thompson", timestamp: "Jan 22, 2026 — 10:00 AM" },
      { action: "Full discovery completed", timestamp: "Jan 22, 2026 — 12:00 PM" },
      { action: "Medical exams scheduled (both applicants)", timestamp: "Jan 23, 2026 — 9:00 AM" },
      { action: "Underwriting submitted to Equitable Life", timestamp: "Jan 25, 2026 — 2:00 PM" },
      { action: "Suitability determination approved", timestamp: "Jan 27, 2026 — 11:00 AM" },
      { action: "Handoff PDF exported", timestamp: "Jan 29, 2026 — 10:00 AM" },
    ],
    aiHistory: [
      { question: "Compare Par WL vs Universal Life for estate planning", response: "For estate planning, Participating Whole Life offers guaranteed death benefit with stable, dividend-enhanced growth, ideal for conservative clients wanting predictability. Universal Life offers more flexibility in premium payments and cash value investment options but with less certainty. For the Sharmas' moderately conservative profile and focus on guaranteed legacy, Equitable EquiPar provides the certainty they're seeking while still offering dividend growth potential based on Equitable's strong dividend history.", timestamp: "Jan 22, 2026 — 11:15 AM" },
    ],
  },
  {
    id: "IFA-2026-012",
    client: "Westcoast Manufacturing Inc. (James & Lisa Wong)",
    age: 46,
    product: "IFA",
    status: "Discovery",
    premium: "$200,000",
    carrier: "TBD (Manulife vs Equitable comparison)",
    advisor: "Sarah Thompson",
    created: "Feb 1, 2026",
    updated: "Today",
    email: "jwong@westcoastmfg.ca",
    phone: "(604) 555-3421",
    dob: "11/20/1980",
    occupation: "Manufacturing Business Owners (CCPC)",
    income: "$650,000 (corporate income, $3.5M retained earnings)",
    riskProfile: "Moderate",
    goals: ["Business Succession", "Balance Sheet Strengthening", "Buy-Sell Funding"],
    notes: "Second-generation family business. Significant corporate surplus. Looking at IFA for balance sheet strengthening and buy-sell agreement funding. Considering coordination with bank financing for premium funding. Meeting with accountant scheduled next week.",
    complianceComplete: false,
    complianceMissing: ["Corporate resolution", "Buy-sell agreement review", "Banking coordination documentation"],
    suitabilityNarrative: "Westcoast Manufacturing Inc.'s substantial retained earnings ($3.5M), the principals' ages (46 & 44), and objectives of business succession and balance sheet strengthening make an Immediate Financing Arrangement the ideal strategy. The IFA will create significant CDA credits for future tax-efficient shareholder distributions, provide NCPI deductions to reduce current corporate taxes, and can be structured to fund buy-sell obligations. The $200,000 annual premium represents prudent deployment of corporate surplus and integrates seamlessly with the company's succession planning goals.",
    timeline: [
      { label: "Case created", date: "Feb 1, 2026", completed: true },
      { label: "Discovery started", date: "Feb 1, 2026", completed: true },
      { label: "Corporate structure analysis", date: "Pending", completed: false },
      { label: "Accountant consultation", date: "Scheduled Feb 7", completed: false },
      { label: "Suitability approved", date: "Pending", completed: false },
    ],
    activityLog: [
      { action: "Case created by Sarah Thompson", timestamp: "Feb 1, 2026 — 1:00 PM" },
      { action: "Discovery Step 1 (Corporate Info) completed", timestamp: "Feb 1, 2026 — 1:30 PM" },
      { action: "Discovery Step 2 (Financial Profile) started", timestamp: "Feb 1, 2026 — 2:00 PM" },
      { action: "Requested T2 tax returns and corporate minute book", timestamp: "Feb 1, 2026 — 2:15 PM" },
    ],
    aiHistory: [
      { question: "How does an IFA integrate with a buy-sell agreement?", response: "An IFA can be structured as cross-purchase or share redemption funding for a buy-sell agreement. When structured properly, the death benefit provides immediate liquidity to fund the buyout of the deceased shareholder's interest. The corporation owns the policy, claims NCPI deductions annually, and upon death, receives the tax-free death benefit (via CDA). These funds can then be distributed tax-free to purchase the deceased's shares from their estate. This provides liquidity, maintains business continuity, and delivers significant tax efficiency compared to other funding methods.", timestamp: "Feb 1, 2026 — 2:30 PM" },
    ],
  },
  {
    id: "UL-2026-015",
    client: "Jennifer Park",
    age: 41,
    product: "Universal Life",
    status: "In Progress",
    premium: "$35,000",
    carrier: "Manulife",
    advisor: "Sarah Thompson",
    created: "Jan 28, 2026",
    updated: "3 days ago",
    email: "jennifer.park@parklaw.ca",
    phone: "(604) 555-8934",
    dob: "04/22/1985",
    occupation: "Lawyer (Professional Corporation)",
    income: "$425,000",
    riskProfile: "Moderate",
    goals: ["Flexible Premium Payments", "Cash Value Growth", "Estate Planning"],
    notes: "Solo practitioner with professional corporation. Income fluctuates year-to-year based on caseload. Wants permanent insurance with flexibility to adjust premiums. Interested in cash value accumulation for potential future policy loans.",
    complianceComplete: true,
    suitabilityNarrative: "Ms. Park's moderate risk profile, variable professional income, and need for premium flexibility make Manulife Universal Life the most appropriate recommendation. Unlike participating whole life, UL allows her to adjust premium payments during lean years while maintaining coverage. The cash value growth provides tax-deferred accumulation, and the policy loan feature offers financial flexibility. The $35,000 target premium is suitable for her income level and provides meaningful death benefit protection while building cash value over time.",
    timeline: [
      { label: "Case created", date: "Jan 28, 2026", completed: true },
      { label: "Discovery started", date: "Jan 28, 2026", completed: true },
      { label: "Medical underwriting", date: "Jan 30, 2026", completed: true },
      { label: "Suitability approved", date: "Pending", completed: false },
      { label: "Handoff package", date: "Pending", completed: false },
    ],
    activityLog: [
      { action: "Case created by Sarah Thompson", timestamp: "Jan 28, 2026 — 11:00 AM" },
      { action: "Discovery completed", timestamp: "Jan 28, 2026 — 12:30 PM" },
      { action: "Medical exam scheduled", timestamp: "Jan 29, 2026 — 9:00 AM" },
      { action: "Underwriting submitted", timestamp: "Jan 30, 2026 — 3:00 PM" },
    ],
    aiHistory: [
      { question: "Explain UL premium flexibility for a professional with variable income", response: "Universal Life is ideal for professionals with fluctuating income because premium payments are flexible within the policy's minimum and maximum limits. In strong income years, Ms. Park can pay above the target premium to build cash value faster. In slower years, she can reduce payments (as long as sufficient cash value exists to cover insurance costs). This flexibility accommodates the natural ebbs and flows of professional practice income while maintaining permanent life insurance coverage.", timestamp: "Jan 28, 2026 — 12:00 PM" },
    ],
  },
  {
    id: "TERM-2026-019",
    client: "Michael & Amanda Rodriguez",
    age: 38,
    product: "Term Life",
    status: "Issued",
    premium: "$2,400",
    carrier: "Equitable Life Canada",
    advisor: "Sarah Thompson",
    created: "Dec 15, 2025",
    updated: "Jan 10, 2026",
    email: "m.rodriguez@email.com",
    phone: "(778) 555-6543",
    dob: "08/14/1988",
    occupation: "School Teacher (Amanda) & Firefighter (Michael)",
    income: "$155,000 (combined)",
    riskProfile: "Conservative",
    goals: ["Mortgage Protection", "Income Replacement", "Children's Education"],
    notes: "Young family with two children (ages 6 and 4). New $800K mortgage. Michael is primary income earner. Need affordable coverage during peak family responsibility years. 20-year term selected to cover until children finish university.",
    complianceComplete: true,
    suitabilityNarrative: "The Rodriguez family's conservative risk profile, primary goal of mortgage and income protection, and budget considerations make a 20-year term life policy the most suitable solution. As Michael is the primary income earner, the $1M death benefit provides appropriate income replacement during the critical years when mortgage obligations and children's education expenses are highest. The $2,400 annual premium is affordable within their budget and provides the necessary protection without overextending financially. The 20-year term aligns with their youngest child reaching age 24.",
    timeline: [
      { label: "Case created", date: "Dec 15, 2025", completed: true },
      { label: "Discovery completed", date: "Dec 15, 2025", completed: true },
      { label: "Medical underwriting", date: "Dec 18, 2025", completed: true },
      { label: "Policy approved", date: "Dec 22, 2025", completed: true },
      { label: "Policy issued", date: "Jan 10, 2026", completed: true },
    ],
    activityLog: [
      { action: "Case created by Sarah Thompson", timestamp: "Dec 15, 2025 — 2:00 PM" },
      { action: "Full discovery completed", timestamp: "Dec 15, 2025 — 3:00 PM" },
      { action: "Medical exams completed (both applicants)", timestamp: "Dec 18, 2025 — 10:00 AM" },
      { action: "Underwriting approved - Preferred rates", timestamp: "Dec 22, 2025 — 11:00 AM" },
      { action: "Policy delivered to clients", timestamp: "Jan 10, 2026 — 2:00 PM" },
    ],
    aiHistory: [],
  },
  {
    id: "IFA-2026-022",
    client: "Pacific Dental Group Inc. (Dr. Kevin Nguyen)",
    age: 53,
    product: "IFA",
    status: "Ready for Handoff",
    premium: "$125,000",
    carrier: "Equitable Life Canada",
    advisor: "Sarah Thompson",
    created: "Jan 10, 2026",
    updated: "2 days ago",
    email: "knguyen@pacificdental.ca",
    phone: "(604) 555-2987",
    dob: "06/22/1973",
    occupation: "Dentist (Professional Corporation)",
    income: "$520,000 (corporate income)",
    riskProfile: "Moderately Conservative",
    goals: ["Tax-Efficient Retirement Savings", "Estate Planning", "CDA Optimization"],
    notes: "Established dental practice with $1.2M corporate surplus. Already maxed RRSP and TFSA. Looking for tax-efficient corporate investment. Wants to create CDA for tax-free retirement income distributions. No debt, practice valued at $3M.",
    complianceComplete: true,
    suitabilityNarrative: "Dr. Nguyen's professional corporation has substantial retained earnings ($1.2M), and his objectives of tax-efficient wealth accumulation and estate planning make an Immediate Financing Arrangement with Equitable EquiPar the ideal solution. The IFA structure will generate Capital Dividend Account credits for tax-free distributions in retirement, provide annual NCPI deductions reducing corporate taxable income, and deliver superior after-tax returns compared to taxable corporate GICs or bonds. The $125,000 annual premium represents prudent deployment of corporate surplus and aligns with his retirement timeline and tax optimization goals.",
    timeline: [
      { label: "Case created", date: "Jan 10, 2026", completed: true },
      { label: "Discovery completed", date: "Jan 10, 2026", completed: true },
      { label: "Corporate tax analysis", date: "Jan 12, 2026", completed: true },
      { label: "Medical underwriting", date: "Jan 15, 2026", completed: true },
      { label: "Suitability approved", date: "Jan 18, 2026", completed: true },
      { label: "Handoff package generated", date: "Jan 20, 2026", completed: true },
    ],
    activityLog: [
      { action: "Case created by Sarah Thompson", timestamp: "Jan 10, 2026 — 9:00 AM" },
      { action: "Discovery completed with accountant present", timestamp: "Jan 10, 2026 — 11:00 AM" },
      { action: "Reviewed corporate T2 returns (3 years)", timestamp: "Jan 12, 2026 — 2:00 PM" },
      { action: "CDA projection analysis completed", timestamp: "Jan 12, 2026 — 3:30 PM" },
      { action: "Medical exam completed - Preferred rating", timestamp: "Jan 15, 2026 — 10:00 AM" },
      { action: "IFA suitability narrative approved", timestamp: "Jan 18, 2026 — 11:00 AM" },
      { action: "Handoff package with CDA illustrations generated", timestamp: "Jan 20, 2026 — 9:00 AM" },
    ],
    aiHistory: [
      { question: "Compare after-tax returns: IFA vs corporate GICs for a BC professional corporation", response: "For a BC professional corporation in the top tax bracket (approximately 27% on passive investment income after 2019 tax changes), corporate GICs earning 4% yield approximately 2.92% after-tax. An IFA with participating whole life provides tax-deferred cash value growth (no annual tax), NCPI deductions reducing corporate taxes, and CDA credits creating tax-free distribution capacity on death. Over 20+ years, the IFA typically delivers superior after-tax wealth accumulation, especially when factoring in estate tax efficiency. Additionally, the death benefit provides estate liquidity and creditor protection not available with GICs.", timestamp: "Jan 12, 2026 — 2:45 PM" },
      { question: "Generate IFA suitability narrative for Pacific Dental Group Inc.", response: "Dr. Nguyen's professional corporation has substantial retained earnings ($1.2M), and his objectives of tax-efficient wealth accumulation and estate planning make an Immediate Financing Arrangement with Equitable EquiPar the ideal solution.", timestamp: "Jan 18, 2026 — 11:00 AM" },
    ],
  },
  {
    id: "PAR-2026-025",
    client: "Robert & Catherine Lee",
    age: 68,
    product: "Participating Whole Life",
    status: "In Progress",
    premium: "$50,000",
    carrier: "Manulife",
    advisor: "Sarah Thompson",
    created: "Feb 3, 2026",
    updated: "1 day ago",
    email: "robert.lee@email.com",
    phone: "(604) 555-7621",
    dob: "09/08/1958",
    occupation: "Retired Business Owners",
    income: "$95,000 (pension + investment income)",
    riskProfile: "Conservative",
    goals: ["Estate Equalization", "Grandchildren's Legacy", "Final Expense Coverage"],
    notes: "Recently sold family business. Have substantial estate ($4M+). Want to leave equal amounts to three adult children and create education fund for five grandchildren. Concerned about probate fees and estate taxes.",
    complianceComplete: true,
    suitabilityNarrative: "The Lees' conservative risk profile, estate planning objectives, and desire for guaranteed wealth transfer make Manulife Participating Whole Life the most appropriate solution. The guaranteed death benefit provides certainty for estate equalization among their three children, while participating dividends offer potential growth. The tax-free death benefit avoids probate and provides immediate liquidity for estate settlement. The $50,000 annual premium (paid from estate assets) represents appropriate allocation for their goals and is well within their means given their $4M+ estate value.",
    timeline: [
      { label: "Case created", date: "Feb 3, 2026", completed: true },
      { label: "Discovery completed", date: "Feb 3, 2026", completed: true },
      { label: "Medical underwriting", date: "Feb 5, 2026", completed: true },
      { label: "Estate planning review", date: "Pending", completed: false },
      { label: "Suitability approval", date: "Pending", completed: false },
    ],
    activityLog: [
      { action: "Case created by Sarah Thompson", timestamp: "Feb 3, 2026 — 10:00 AM" },
      { action: "Discovery completed", timestamp: "Feb 3, 2026 — 11:30 AM" },
      { action: "Reviewed will and estate plan", timestamp: "Feb 4, 2026 — 2:00 PM" },
      { action: "Medical exams scheduled (both applicants)", timestamp: "Feb 5, 2026 — 9:00 AM" },
    ],
    aiHistory: [
      { question: "How does life insurance help with estate equalization?", response: "When parents have unequal assets to distribute (e.g., a family business going to one child), life insurance provides liquidity to equalize estates. The death benefit can be left to the children not receiving the business, ensuring fair treatment. Additionally, the tax-free death benefit avoids probate, provides immediate liquidity for estate taxes or debts, and can be structured to flow directly to beneficiaries outside the estate. For the Lees with three children and $4M+ in assets, life insurance ensures equal inheritance while minimizing estate settlement costs and delays.", timestamp: "Feb 3, 2026 — 11:00 AM" },
    ],
  },
  {
    id: "UL-2026-028",
    client: "Thompson Family Holdings Inc. (Mark & Susan Thompson)",
    age: 60,
    product: "Universal Life",
    status: "Review",
    premium: "$100,000",
    carrier: "Equitable Life Canada",
    advisor: "Sarah Thompson",
    created: "Jan 25, 2026",
    updated: "Today",
    email: "mark@thompsonfamily.ca",
    phone: "(250) 555-3492",
    dob: "02/14/1966",
    occupation: "Real Estate Investors (Holding Company)",
    income: "$780,000 (rental income + capital gains)",
    riskProfile: "Moderate",
    goals: ["Estate Tax Efficiency", "Asset Protection", "Liquidity for Estate Settlement"],
    notes: "Substantial real estate portfolio ($8M+) held in family holding company. Concerned about estate taxes and liquidity. Want permanent insurance to provide tax-free death benefit for estate settlement costs. Considering UL for premium flexibility as rental income varies.",
    complianceComplete: true,
    suitabilityNarrative: "Thompson Family Holdings Inc.'s substantial real estate holdings ($8M+), the principals' ages (60 & 58), and objectives of estate tax efficiency and liquidity make Universal Life corporate-owned insurance highly suitable. The UL structure provides premium flexibility to accommodate variable rental income, tax-deferred cash value growth, and NCPI deductions. The death benefit creates CDA credits for tax-free distributions and provides immediate liquidity for estate settlement without forcing real estate sales. The $100,000 annual premium appropriately addresses their estate planning needs while maintaining flexibility for their rental income cash flows.",
    timeline: [
      { label: "Case created", date: "Jan 25, 2026", completed: true },
      { label: "Discovery completed", date: "Jan 25, 2026", completed: true },
      { label: "Estate planning analysis", date: "Jan 27, 2026", completed: true },
      { label: "Medical underwriting", date: "Jan 30, 2026", completed: true },
      { label: "Suitability approved", date: "Feb 2, 2026", completed: true },
      { label: "Final review with accountant", date: "Scheduled Feb 10", completed: false },
    ],
    activityLog: [
      { action: "Case created by Sarah Thompson", timestamp: "Jan 25, 2026 — 1:00 PM" },
      { action: "Discovery completed with estate lawyer present", timestamp: "Jan 25, 2026 — 3:00 PM" },
      { action: "Reviewed real estate portfolio and holding company structure", timestamp: "Jan 27, 2026 — 10:00 AM" },
      { action: "Projected estate tax liability analysis", timestamp: "Jan 27, 2026 — 11:30 AM" },
      { action: "Medical exams completed", timestamp: "Jan 30, 2026 — 2:00 PM" },
      { action: "Suitability determination approved", timestamp: "Feb 2, 2026 — 9:00 AM" },
      { action: "Scheduled final review with accountant for Feb 10", timestamp: "Feb 3, 2026 — 11:00 AM" },
    ],
    aiHistory: [
      { question: "How does corporate-owned UL provide estate liquidity for real estate portfolios?", response: "For families with substantial real estate holdings, corporate-owned Universal Life provides critical estate liquidity without forced property sales. Upon death, the policy death benefit is received by the holding company tax-free, creates CDA credits allowing tax-free distribution to estate/heirs, and provides immediate cash to pay estate settlement costs, capital gains taxes, or equalize inheritances. This prevents the common problem of 'asset rich, cash poor' estates that must sell properties quickly (often at unfavorable prices) to meet tax obligations. The UL format offers premium flexibility to accommodate variable rental income cycles.", timestamp: "Jan 27, 2026 — 11:00 AM" },
    ],
  },
];

export const ALL_STATUSES: CaseStatus[] = ["Discovery", "In Progress", "Review", "Ready for Handoff", "Issued"];
export const ALL_PRODUCTS: ProductType[] = ["IFA", "Participating Whole Life", "Universal Life", "Term Life"];
